import {
    StyleSheet

} from "react-native";
import Colors from "../../../constant/colors";


const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.white },
    mapWrap: { flex: 1 },
    headerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        paddingTop: 12,
        paddingHorizontal: 14,
    },
    headerTitle: { color: '#fff', fontWeight: '900', fontSize: 22, marginBottom: 10 },
    searchPill: {
        backgroundColor: 'rgba(17,18,20,0.92)',
        borderRadius: 16,
        paddingHorizontal: 12,
        height: 48,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    searchIcon: { color: 'rgba(255,255,255,0.7)', fontWeight: '900' },
    searchInput: { flex: 1, color: '#fff', fontWeight: '800' },
    headerRightBtn: {
        backgroundColor: '#6C63FF',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
    },
    headerRightBtnText: { color: '#fff', fontWeight: '900', fontSize: 12 },
    segmentRow: { marginTop: 10, flexDirection: 'row', gap: 8 },
    segmentBtn: {
        flex: 1,
        height: 34,
        borderRadius: 999,
        backgroundColor: 'rgba(17,18,20,0.75)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 8,
    },
    segmentBtnActive: { backgroundColor: '#6C63FF' },
    segmentText: { color: 'rgba(255,255,255,0.85)', fontWeight: '900', fontSize: 12 },
    segmentTextActive: { color: '#fff' },
    cardsWrap: {
        
    },
    cardsContent: {
        paddingHorizontal: 12,
        gap: 10,
    },
    driverCard: {
        width: 260,
        backgroundColor: '#fff',
        borderRadius: 18,
        padding: 14,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 8 },
        elevation: 3,
    },
    driverCardRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    driverName: { fontSize: 16, fontWeight: '900', color: '#111214', marginBottom: 4 },
    driverMeta: { color: '#6B7280', fontWeight: '800' },
    pillBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
    pillBadgeOn: { backgroundColor: 'rgba(34,197,94,0.15)' },
    pillBadgeOff: { backgroundColor: 'rgba(107,114,128,0.12)' },
    pillBadgeText: { fontWeight: '900', fontSize: 12 },
    pillBadgeTextOn: { color: '#16A34A' },
    pillBadgeTextOff: { color: '#6B7280' },
    driverStatsRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
    driverStat: { flex: 1 },
    driverStatLabel: { color: '#9CA3AF', fontWeight: '900', fontSize: 11, marginBottom: 4 },
    driverStatValue: { color: '#111214', fontWeight: '900' },
    driverDetailsMiniBtn: {
        marginTop: 12,
        alignSelf: 'flex-start',
        backgroundColor: '#6C63FF',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
    },
    driverDetailsMiniText: { color: '#fff', fontWeight: '900' },
    loadingOverlay: {
        position: 'absolute',
        top: 12,
        right: 12,
        backgroundColor: 'rgba(255,255,255,0.9)',
        padding: 8,
        borderRadius: 10,
    },
    errorOverlay: {
        position: 'absolute',
        bottom: 16,
        left: 16,
        right: 16,
        backgroundColor: 'rgba(255,255,255,0.95)',
        padding: 12,
        borderRadius: 12,
    },
    errorText: { color: Colors.ERROR[200], fontWeight: '700', marginBottom: 8 },
    retryBtn: {
        alignSelf: 'flex-start',
        backgroundColor: Colors.PRIMARY[100],
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 10,
    },
    retryText: { color: Colors.white, fontWeight: '700' },
    offlineHint: {
        position: 'absolute',
        bottom: 16,
        right: 16,
        backgroundColor: 'rgba(0,0,0,0.7)',
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 10,
    },
    offlineHintText: { color: Colors.white, fontWeight: '700', fontSize: 12 },
    modal: { justifyContent: 'flex-end', margin: 0 },
    card: {
        backgroundColor: Colors.white,
        padding: 16,
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
    },
    cardTitle: { fontSize: 18, fontWeight: '800', color: Colors.black_2, marginBottom: 6 },
    cardMeta: { color: Colors.NEUTRAL[300], marginBottom: 6, fontWeight: '600' },
    detailsBtn: {
        marginTop: 8,
        backgroundColor: Colors.PRIMARY[100],
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
    },
    detailsBtnText: { color: Colors.white, fontWeight: '800' },
});

export default styles;