import { StyleSheet } from "react-native";
import { Colors } from "../../../constant";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F4F6F9" },
  header: {
    backgroundColor: Colors.PRIMARY[100],
    paddingTop: 14,
    paddingBottom: 14,
    paddingHorizontal: 14,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerIconText: { color: "#fff", fontWeight: "900", fontSize: 18 },
  headerTitle: { color: "#fff", fontWeight: "900", fontSize: 22 },
  searchPill: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  searchIcon: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 16,
    fontWeight: "900",
  },
  searchInput: { flex: 1, color: "#fff", fontWeight: "700" },
  segmentRow: { marginTop: 12, flexDirection: "row", gap: 8 },
  segmentBtn: {
    flex: 1,
    height: 34,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  segmentBtnActive: {
    backgroundColor: "#fff",
  },
  segmentText: {
    color: "rgba(255,255,255,0.85)",
    fontWeight: "800",
    fontSize: 12,
  },
  segmentTextActive: { color: Colors.PRIMARY[400] },
  center: { padding: 16 },
  errorText: { color: Colors.ERROR[200], fontWeight: "800", marginBottom: 10 },
  retryBtn: {
    alignSelf: "flex-start",
    backgroundColor: "#6C63FF",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  retryText: { color: Colors.white, fontWeight: "800" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  cardTopRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatarWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#E9ECF2",
  },
  avatar: { width: "100%", height: "100%" },
  name: { fontSize: 16, fontWeight: "900", color: "#111214", marginBottom: 2 },
  meta: { color: "#6B7280", fontWeight: "800" },
  badge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  badgeFav: { backgroundColor: "rgba(34,197,94,0.15)" },
  badgeNeutral: { backgroundColor: "rgba(107,114,128,0.12)" },
  badgeText: { fontWeight: "900", fontSize: 12 },
  badgeTextFav: { color: "#16A34A" },
  badgeTextNeutral: { color: "#6B7280" },
  cardDivider: { height: 1, backgroundColor: "#EEF0F5", marginVertical: 12 },
  cardBottomRow: { flexDirection: "row", gap: 12 },
  stat: { flex: 1 },
  statLabel: {
    color: "#9CA3AF",
    fontWeight: "900",
    fontSize: 11,
    marginBottom: 4,
  },
  statValue: { color: "#111214", fontWeight: "900" },
});

export default styles